name: Deploy Main & WIP Branches

on:
  workflow_dispatch:
    inputs:
      deploy_main:
        description: 'Deploy main branch'
        required: false
        default: 'true'
      deploy_wip:
        description: 'Deploy wip branch'
        required: false
        default: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Disable automatic token persistence

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ensure Node.js version 16 is used

    - name: Install dependencies
      run: npm install

    - name: Build main branch
      if: ${{ github.event.inputs.deploy_main == 'true' }}
      env:
        BASE_URL: /LanguageLearning/
      run: |
        git fetch origin main
        git checkout main
        npm run build || exit 1  # Exit if build fails
        mkdir -p ./deploy
        mv ./dist/* ./deploy/ || exit 1  # Exit if mv fails

    - name: Build wip branch
      if: ${{ github.event.inputs.deploy_wip == 'true' }}
      env:
        BASE_URL: /LanguageLearning/wip/
      run: |
        git fetch origin wip
        git checkout wip
        npm run build || exit 1  # Exit if build fails
        mkdir -p ./deploy/wip
        mv ./dist/* ./deploy/wip/ || exit 1  # Exit if mv fails

    - name: Verify GITHUB_TOKEN
      run: |
        if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
          echo "GITHUB_TOKEN is not set"
          exit 1
        else
          echo "✅ GITHUB_TOKEN exists and is set!"
        fi

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./deploy
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git push --force origin master:gh-pages